name: movie_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter_sdk: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.3
  
  # realiza la comparacion de objetos automaticamente (equals())
  equatable: ^2.0.3
  # permite realizar llamadas http
  http: ^0.13.3
  # permite realizar un return entre dos tipos de clases y actuar a corde
  dartz: ^0.10.0
  # para di(dependency injection)
  get_it: ^7.2.0
  # google fonts
  google_fonts: ^2.1.0
  # bloc design pattern
  flutter_bloc: ^7.3.0
  # handle svgs files
  flutter_svg: ^0.22.0
  # to load images from internet
  cached_network_image: ^3.1.0
  # to i18n
  flutter_localizations:
    sdk: flutter
  # feedback module
  wiredash: ^0.7.0+1
  # playing/stream YouTube videos inline
  youtube_player_flutter: ^8.0.0
  # local dba
  hive: ^2.0.4
  path_provider: ^2.0.5
  # animations on rive app
  flare_flutter: ^3.0.2

dev_dependencies:
  hive_generator: ^1.1.1
  build_runner: ^2.1.2
  test: ^1.17.10
  bloc_test: ^8.2.0
  mockito: ^5.0.16
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/animations/
    - assets/svgs/
    - assets/pngs/
    - assets/jpgs/
    - assets/languages/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
